### ISSUE TITLE
Can not see created API

### ISSUE THREAD

**Issue by tasmaniski** [zfcampus/zf-apigility-admin#323]
Hello, 

The problem is simple, I just created a new API via admin-ui. 
So new module is created with base structure in it. 
Also modules.config.php is updated with new module. 

But I can't see that new Api on admin. 
which leads that I can't work further with admin - can not create any rpc or rest services.

**Comment by gabrielsomoza** [comment]
Are you by any chance seeing the same errors in the browser's console as one of these tickets: #312 or #325 ? Even if not, I'd follow the same procedure I mentioned there just in case.

Otherwise: did you only create the new API and that's it? No additional code-changes? If so, I'd recommend:
* Check server logs to see if there were any errors while creating the API. That could have meant that the skeleton was only partially created, leaving things unstable. Having a VCS like Git can help in this situation: not only to revert but also to see to what extent files were created or not.
* Double-check file permissions (that could have been another cause) and make sure the web server can write to those directories.

**Comment by tasmaniski** [comment]
No,  

if I first change application config file I will not be able to create API from admin in the app config file.
So the issue was in that - I changed app config before I create any API.

**Comment by gabrielsomoza** [comment]
Oh ok, so the issue is fixed for you now?

**Comment by tasmaniski** [comment]
It's fixed for me, but the issue is still there :) 
So if someone try to use apigility-admin, 
need to be sure that didn't change the config before.

**Comment by gabrielsomoza** [comment]
Gotcha, thanks for the heads-up! If people regularly bump into this it might be useful to add some kind of warning about it in the README or other docs.

**Comment by tasmaniski** [comment]
Yeah, that would be fine  :)

**Comment by weierophinney** [comment]
This repository has been closed and moved to laminas-api-tools/api-tools-admin; a new issue has been opened at https://github.com/laminas-api-tools/api-tools-admin/issues/27.
